FROM python:3.8

# Install OS dependencies
RUN apt update && \
  apt install telnet -y && \
  rm -rf /var/lib/apt/lists/*

# Deploy application
WORKDIR /lms
COPY requirements.txt /lms
COPY lms-app /lms/lms-app

# Install application dependencies
RUN pip install -r requirements.txt

# Entrypoint to start application
# gunicorn --chdir lms-app -w 2 --threads 2 -b 0.0.0.0:5000 main:app
CMD ["gunicorn", "--chdir", "lms-app", "-w", "2", "--threads", "2", "-b", "0.0.0.0:5000", "main:app"]